name: Coverage

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: pypy3
    - name: Ensure we have new enough versions to respect python_version
      run: python -m pip install -U pip setuptools
    - name: Install tox
      run: python -m pip install tox
    - name: Collect & Upload Coverage
      run: python -m tox -e pypy3-format-codecov
      env:
        CODECOV_TOKEN: 2b38dae1-41c4-4435-a29d-79a1299e5617
